name: codio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  cloud_firestore: ^5.0.2
  rxdart: ^0.28.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/covers/
    - assets/congrats.gif

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: "launcher_icon"
  ios: "AppIcon"
  image_path_ios: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
